version: "3"
services: 
  buildapp:
    build: docfile
    volumes: 
      - type: bind
        source: /home/shara
        target: /usr/local/tomcat/webapps

  web:
    image: tomcat
    volumes: 
      - "/home/shara:/usr/local/tomcat/webapps"