version: "3"
services:
  buildapp:
    build: docfile
    volumes:
      - type: volume
        source: openopen
        target: /usr/local/tomcat/webapps
      

  web:
    image: tomcat
    volumes:
      - type: bind
        source: openopen
        target: /usr/local/tomcat/webapps
    ports:
      - "8080:8080"
volumes:
  openopen